
export interface StoryLine {
  speaker: string;
  text: string;
  color: string;
}

export const strings = {
  mr: {
    storyDialogue: [
      { speaker: "छत्रपती शिवाजी महाराज", text: "बाजी, सुलतानशाहीचे सैन्य अगणित आहे. मला विशालगडावर पोहोचायला हवे — तिथून प्रतिकाराची हाक द्यायची आहे.", color: "text-orange-400" },
      { speaker: "बाजीप्रभू देशपांडे", text: "जा, महाराज. वेग हेच तुमचे कवच. मी या घाटाला पोलादाची भिंत बनवतो.", color: "text-white" },
      { speaker: "छत्रपती शिवाजी महाराज", text: "दहा हजारांसमोर तीनशे... हे ओझे फार मोठे आहे, बंधू.", color: "text-orange-400" },
      { speaker: "बाजीप्रभू देशपांडे", text: "हे ओझे नाही, हा मान आहे. तिसरा तोफेचा आवाज येईपर्यंत एकही पाकळी त्यांच्या पायाखाली येणार नाही. हर हर महादेव!", color: "text-white" },
    ] as StoryLine[],
    ui: {
      vitality: "प्राणशक्ती",
      spirit: "उत्साह",
      valor: "पराक्रम",
      elitesSlain: "शत्रू निपात",
      wave: "लाट",
      weaponLv: "शस्त्र स्तर",
      nextPerk: "पुढील वरदान",
      holdTheLine: "थांबा — रक्षा करा",
      valorReady: "पराक्रम सज्ज · V दाबा",
      incomingArrow: "बाण येतो · टाळा",
      choosePath: "तुमचा मार्ग निवडा",
      perkUnlocked: "युद्ध वरदान मिळाले",
      paused: "विराम",
      holdLine: "रक्षा करा",
      resume: "पुढे",
      controls: "नियंत्रणे",
      quit: "बाहेर",
      quitConfirm: "रणभूमी सोडायची?",
      quitToMenu: "सुरुवातीला जा",
      continueBtn: "पुढे चला",
      viewScorecard: "गुणपत्रक पहा",
      shareCard: "शेअर करा",
      playAgain: "पुन्हा खेळा",
      harHarMahadev: "हर हर महादेव",
      chooseMode: "तुमची लढाई निवडा",
      selectMode: "प्रकार निवडा",
      skirmish: "चकमक",
      battle: "लढाई",
      lastStand: "अखेरचा प्रतिकार",
    },
    combo: {
      fury: "प्रकोप",
      onslaught: "आक्रमण",
      mythic: "अद्भुत",
    },
    scorecard: {
      kingSafe: "महाराज सुरक्षित",
      bajiFallen: "बाजीप्रभू पडले",
      elitesSlain: "शत्रू निपात",
      maxCombo: "सर्वोच्च कॉम्बो",
      damageTaken: "नुकसान",
      valorStrikes: "पराक्रम प्रहार",
      objectivesCompleted: "उद्दिष्टे पूर्ण",
      coins: "स्वराज्य नाणी",
      rank: "पद",
      newBest: "नवीन सर्वोत्तम!",
    },
    vishalgad: {
      title: "शिवाजी महाराज विशालगडावर पोहोचले",
      subtitle: "विशालगड",
      text: "संकेत पाठवला. घाट टिकला. तुमच्या प्रतिकारामुळे इतिहास बदलला.",
    },
    medals: {
      wallOfSteel: "पोलादाची भिंत",
      relentless: "प्रतापगडाची छाया",
      valorous: "अफझलखानाचा काळ",
      bannerHolder: "सिंहगडाची गर्जना",
    },
    battleCries: ["हर हर महादेव!", "जय भवानी!", "प्रहार!"],
    historicalTips: [
      "पावनखिंडची लढाई जुलै १६६०मध्ये झाली — बाजीप्रभूंच्या ३०० मावळ्यांनी सिद्दी मसूदच्या हजारो सैनिकांना घाटात रोखले.",
      "बाजीप्रभू देशपांडे दोन तलवारी एकत्र चालवत — एक हल्ल्यासाठी, एक बचावासाठी.",
      "विशालगडावरून तीन तोफांचा आवाज म्हणजे महाराज सुरक्षित पोहोचल्याचा संकेत होता.",
      "पावनखिंड हा सह्याद्रीतील अरुंद घाट आहे — इथे मोजक्या शूरांनी हजारोंना रोखणे शक्य होते.",
      "बाजीप्रभूंनी तिसरा तोफेचा आवाज ऐकेपर्यंत जखमी होऊनही लढत राहिले.",
      "शिवाजी महाराजांनी या घाटाचे नाव 'पावनखिंड' ठेवले — पवित्र घाट — बाजीप्रभूंच्या बलिदानाच्या स्मरणार्थ.",
      "मराठा सैन्यात 'हवालदार' ते 'सरनौबत' अशी पदे होती — प्रत्येक पद पराक्रमाने मिळवायचे.",
      "सिंहगडची लढाई (१६७०) — तानाजी मालुसरेंनी किल्ला जिंकला, पण प्राणांचे बलिदान दिले.",
      "प्रतापगडच्या लढाईत (१६५९) शिवाजी महाराजांनी अफझलखानाचा वध केला — हा स्वराज्याचा पहिला मोठा विजय.",
      "मावळे — सह्याद्रीच्या दऱ्याखोऱ्यातील योद्धे — शिवाजी महाराजांच्या सैन्याचा कणा होते.",
    ],
    modes: {
      skirmish: { name: "चकमक", desc: "९० सेकंद — घाट राखा", unlock: "उपलब्ध" },
      battle: { name: "लढाई", desc: "३ मिनिटे — जोरदार प्रतिकार", unlock: "१ चकमक पार करा" },
      lastStand: { name: "अखेरचा प्रतिकार", desc: "५ मिनिटे — तीनशेंची लढाई", unlock: "१ लढाई पार करा" },
    },
    daily: {
      title: "आजची लढाई",
      completed: "पूर्ण",
      bonus: "बोनस: +१५ नाणी",
      best: "सर्वोत्तम",
    },
    start: {
      subtitle: "स्वराज्य कथा",
      title: "पावनखिंड",
      tagline: "तीनशेंचा प्रतिकार",
      description: "डोंगर घाट थरथरतो. पोलाद बोलेल. तिसऱ्या तोफेच्या आवाजापर्यंत थांबा.",
      witnessVow: "शपथ पहा",
      drawBlade: "तलवार उचला",
    },
  },
  en: {
    storyDialogue: [
      { speaker: "Shivaji Maharaj", text: "Baji, the Sultanate's numbers are overwhelming. I must reach Vishalgad to signal the resistance.", color: "text-orange-400" },
      { speaker: "Baji Prabhu", text: "Go, Maharaj. Speed is your shield. I shall turn this pass into a wall of steel.", color: "text-white" },
      { speaker: "Shivaji Maharaj", text: "300 against 10,000... This is a heavy burden I place on your shoulders, my brother.", color: "text-orange-400" },
      { speaker: "Baji Prabhu", text: "It is not a burden, but an honor. Till the third cannon sounds, not a single petal shall be crushed by their boots. Har Har Mahadev!", color: "text-white" },
    ] as StoryLine[],
    ui: {
      vitality: "Vitality",
      spirit: "Spirit",
      valor: "Valor",
      elitesSlain: "ELITES SLAIN",
      wave: "Wave",
      weaponLv: "Weapon Lv",
      nextPerk: "Next perk",
      holdTheLine: "Hold the Line",
      valorReady: "Valor Ready · Press V",
      incomingArrow: "Incoming Arrow · Dodge",
      choosePath: "Choose Your Path",
      perkUnlocked: "War Perk Unlocked",
      paused: "Paused",
      holdLine: "Hold the Line",
      resume: "Resume (P)",
      controls: "Controls (C)",
      quit: "Quit (Q)",
      quitConfirm: "Leave the battlefield?",
      quitToMenu: "Quit to Menu",
      continueBtn: "CONTINUE",
      viewScorecard: "View Scorecard",
      shareCard: "Share Card",
      playAgain: "Play Again",
      harHarMahadev: "Har Har Mahadev",
      chooseMode: "Choose Your Battle",
      selectMode: "Select Mode",
      skirmish: "Skirmish",
      battle: "Battle",
      lastStand: "Last Stand",
    },
    combo: {
      fury: "FURY",
      onslaught: "ONSLAUGHT",
      mythic: "MYTHIC",
    },
    scorecard: {
      kingSafe: "The King is Safe",
      bajiFallen: "Baji Prabhu has Fallen",
      elitesSlain: "Sultanate Elites Slain",
      maxCombo: "Max Combo",
      damageTaken: "Damage Taken",
      valorStrikes: "Valor Strikes",
      objectivesCompleted: "Objectives Completed",
      coins: "Swarajya Coins",
      rank: "Rank",
      newBest: "New Personal Best!",
    },
    vishalgad: {
      title: "Shivaji Maharaj Reaches Vishalgad",
      subtitle: "Vishalgad",
      text: "The signal is sent. The pass holds. History turns with your stand.",
    },
    medals: {
      wallOfSteel: "Wall of Steel",
      relentless: "Pratapgad's Shadow",
      valorous: "Afzal Khan's Bane",
      bannerHolder: "Sinhagad's Echo",
    },
    battleCries: ["Har Har Mahadev!", "Jai Bhavani!", "Prahar!"],
    historicalTips: [
      "The Battle of Pavan Khind took place in July 1660 — Baji Prabhu's 300 Mavlas held thousands of Siddi Masud's troops in the narrow pass.",
      "Baji Prabhu Deshpande fought with two swords simultaneously — one for attack, one for defense.",
      "Three cannon shots from Vishalgad was the signal that Shivaji Maharaj had reached safety.",
      "Pavan Khind is a narrow mountain pass in the Sahyadris — here, a few brave warriors could hold back thousands.",
      "Baji Prabhu continued fighting despite severe wounds until the third cannon sounded.",
      "Shivaji Maharaj renamed this pass 'Pavankhind' — the Sacred Pass — in memory of Baji Prabhu's sacrifice.",
      "The Maratha army had ranks from 'Havaldar' to 'Sarnaubat' — each earned through valor in battle.",
      "The Battle of Sinhagad (1670) — Tanaji Malusare captured the fort but gave his life in the process.",
      "At the Battle of Pratapgad (1659), Shivaji Maharaj slew Afzal Khan — this was Swarajya's first great victory.",
      "Mavlas — warriors from the valleys of the Sahyadris — formed the backbone of Shivaji Maharaj's army.",
    ],
    modes: {
      skirmish: { name: "Skirmish", desc: "90 seconds — Hold the pass", unlock: "Unlocked" },
      battle: { name: "Battle", desc: "3 minutes — Fierce resistance", unlock: "Survive 1 Skirmish" },
      lastStand: { name: "Last Stand", desc: "5 minutes — The full stand of 300", unlock: "Survive 1 Battle" },
    },
    daily: {
      title: "Daily Challenge",
      completed: "Completed",
      bonus: "Bonus: +15 coins",
      best: "Best",
    },
    start: {
      subtitle: "Swarajya Chronicles",
      title: "Pavankhind",
      tagline: "The Stand of the 300",
      description: "The mountain pass trembles. Steel will speak. Hold the line until the third cannon cries.",
      witnessVow: "WITNESS THE VOW",
      drawBlade: "DRAW YOUR BLADE",
    },
  },
};

export type Lang = 'mr' | 'en';
export type Strings = typeof strings.mr;
